apiVersion: apps/v1
kind: Deployment
metadata:
  name: opaque
  labels:
    app: opaque
spec:
  selector:
    matchLabels:
      app: opaque
  template:
    metadata:
      labels:
        app: opaque
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: bjoernpetersen.net/location
                    operator: In
                    values:
                      - europe
      imagePullSecrets:
        - name: github
      containers:
        - name: api
          image: {{ .Values.image }}
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 8080
              path: /
