name: opaque_server
version: 0.1.0

publish_to: none

environment:
  sdk: ^2.15.0

dependencies:
  opaque:
    path: ../core

  shelf: ^1.0.0
  shelf_router: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  opaque_lints:
    path: ../lints
  test: ^1.0.0
