name: App
on: [push]

jobs:
  generate:
    name: Code Generation
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v1
      - name: Initialize Cache
        uses: actions/cache@v2
        with:
          key: ${{ hashFiles('app/pubspec.lock') }}-${{ github.sha }}
          restore-keys: |
            ${{ hashFiles('app/pubspec.lock') }}-
          path: |
            /opt/hostedtoolcache/flutter/
            app/.dart_tool/
            app/lib/**/*.g.dart
            app/test/**/*.g.dart
            app/lib/**/*.config.dart
            app/test/**/*.config.dart
            app/lib/**/*.i18n.dart
            app/test/**/*.i18n.dart
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Get Dependencies
        run: flutter pub get
        working-directory: ./app
      - name: Run Code Generation
        run: flutter pub run build_runner build
        working-directory: ./app

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v1
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          key: ${{ hashFiles('app/pubspec.lock') }}-${{ github.sha }}
          restore-keys: |
            ${{ hashFiles('app/pubspec.lock') }}-
          path: |
            /opt/hostedtoolcache/flutter/
            app/.dart_tool/
            app/lib/**/*.g.dart
            app/test/**/*.g.dart
            app/lib/**/*.config.dart
            app/test/**/*.config.dart
            app/lib/**/*.i18n.dart
            app/test/**/*.i18n.dart
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Run Tests
        run: flutter test --no-pub
        working-directory: ./app

  check_format:
    name: Check Format
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v1
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          key: ${{ hashFiles('app/pubspec.lock') }}-${{ github.sha }}
          restore-keys: |
            ${{ hashFiles('app/pubspec.lock') }}-
          path: |
            /opt/hostedtoolcache/flutter/
            app/.dart_tool/
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Check lib formatting
        run: flutter format lib --set-exit-if-changed
        working-directory: ./app
      - name: Check test formatting
        run: flutter format test --set-exit-if-changed
        working-directory: ./app

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v1
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          key: ${{ hashFiles('app/pubspec.lock') }}-${{ github.sha }}
          restore-keys: |
            ${{ hashFiles('app/pubspec.lock') }}-
          path: |
            /opt/hostedtoolcache/flutter/
            app/.dart_tool/
            app/lib/**/*.g.dart
            app/test/**/*.g.dart
            app/lib/**/*.config.dart
            app/test/**/*.config.dart
            app/lib/**/*.i18n.dart
            app/test/**/*.i18n.dart
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Run Analysis
        run: flutter analyze
        working-directory: ./app
