name: Core-Tests
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: dart:2.14
    steps:
      - name: Check out repo
        uses: actions/checkout@v1
      - name: Get dependencies
        run: pub get
        working-directory: ./core
      - name: Run code generation
        run: pub run build_runner build
        working-directory: ./core
      - name: Run tests
        run: dart test
        working-directory: ./core

  check_format:
    name: Check Format
    runs-on: ubuntu-latest
    container: dart:2.14
    steps:
      - name: Check out repo
        uses: actions/checkout@v1
      - name: Check lib formatting
        run: dart format lib --set-exit-if-changed
        working-directory: ./core
      - name: Check test formatting
        run: dart format test --set-exit-if-changed
        working-directory: ./core

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: dart:2.14
    steps:
      - name: Check out repo
        uses: actions/checkout@v1
      - name: Get dependencies
        run: pub get
        working-directory: ./core
      - name: Run code generation
        run: pub run build_runner build
        working-directory: ./core
      - name: Run Analysis
        run: dart analyze
        working-directory: ./core
